#!/bin/bash
mkdir -p ./libs
mkdir -p ./obj
mkdir -p ../../libs  # sdk-native/libs
# git submodule init
# git submodule update
# missing from the commit we are using. if we build latest breakpad, might be removed
cp -r ./lss ./breakpad/src/third_party

# countly_breakpad.cpp includes breakpad/src/config.h for VERSION and CLY_HEAD_CHECKSUM. Autotools
# normally generates that header, which needs a toolchain not present on every build machine, and
# none of the breakpad sources ndk-build compiles include it. So write the two macros directly.
breakpadVersion=$(sed -n 's/^AC_INIT(breakpad, \([^,]*\),.*/\1/p' ./breakpad/configure.ac)
breakpadChecksum=$(git -C ./breakpad rev-parse --short HEAD)
cat > ./breakpad/src/config.h <<EOF
/* Generated by prepare.sh, do not edit. */
#define VERSION "${breakpadVersion}"
#define CLY_HEAD_CHECKSUM "${breakpadChecksum}"
EOF
echo "Generated breakpad/src/config.h for breakpad ${breakpadVersion} (${breakpadChecksum})."

echo "Preparation done. You can now execute build.sh."
