#!/bin/bash
mkdir -p ./libs
mkdir -p ./obj
mkdir -p ../../libs  # sdk-native/libs
# git submodule init
# git submodule update
# linux_syscall_support is a DEPS dependency of breakpad, not part of its tree. The copy in ./lss is
# the revision breakpad's DEPS pins (29164a80da4d41134950d76d55199ea33fbb9613); update both together.
cp -r ./lss ./breakpad/src/third_party

# countly_breakpad.cpp includes breakpad/src/config.h for VERSION and CLY_HEAD_CHECKSUM. Autotools
# normally generates that header, which needs a toolchain not present on every build machine, and
# none of the breakpad sources ndk-build compiles include it. So write the two macros directly.
# Matches both AC_INIT(breakpad, 0.1+cly, ...) and the bracketed AC_INIT([breakpad],[0.1+cly],...).
breakpadVersion=$(sed -n 's/^AC_INIT(\[\{0,1\}breakpad\]\{0,1\}, *\[\{0,1\}\([^],]*\)\]\{0,1\},.*/\1/p' ./breakpad/configure.ac)
if [ -z "$breakpadVersion" ]; then
    echo "Could not read the breakpad version from breakpad/configure.ac. Stopping rather than baking an empty version string."
    exit 1
fi
breakpadChecksum=$(git -C ./breakpad rev-parse --short HEAD)
cat > ./breakpad/src/config.h <<EOF
/* Generated by prepare.sh, do not edit. */
#define VERSION "${breakpadVersion}"
#define CLY_HEAD_CHECKSUM "${breakpadChecksum}"
EOF
echo "Generated breakpad/src/config.h for breakpad ${breakpadVersion} (${breakpadChecksum})."

echo "Preparation done. You can now execute build.sh."
